name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast-bandit:
    name: SAST - Bandit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Bandit
        run: pip install bandit

      - name: Ejecutar Bandit (falla si hay severidad media o alta)
        working-directory: ./app
        run: bandit -r . -l -x ./test_app.py

  container-scan-trivy:
    name: Container Scan - Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Construir imagen para escanear
        run: docker build -t flask-api:scan ./app

      - name: Ejecutar Trivy (falla si hay CRITICAL/HIGH)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: flask-api:scan
          severity: "CRITICAL,HIGH"
          exit-code: "1"
          ignore-unfixed: true

  test:
    name: Pruebas unitarias (Pytest)
    needs: [sast-bandit, container-scan-trivy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        working-directory: ./app
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Ejecutar Pytest
        working-directory: ./app
        run: pytest -v

  deploy:
    name: Deploy a producción
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Desplegar por SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/proyecto-sre
            git pull origin main
            docker compose down
            docker compose up -d --build